version: "3"
services:
  rerouterr:
    restart: unless-stopped
    container_name: rerouterr
    build: .
#    image: leojay/rerouterr:latest
    hostname: rerouterr
    ports:
      - "7777:7777"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes: 
      - path/to/Rerouterr:/config # change me
      - /etc/localtime:/etc/localtime:ro
